apiVersion: v1
kind: Service
metadata:
  name: student-timetable-service
  labels:
    app: student-timetable
spec:
  type: NodePort
  selector:
    app: student-timetable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081